spring.application.name=redisdemo

#Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
#deleting individual key
#spring.cache.redis.time-to-live=5000

#MySQL database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/redisdb?
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#Enable SQL logging
spring.jpa.show-sql=true

#cache TTL for deleting all keys
caching.productTTL=5000